Build 5.1
 Fix -Wc++98-compat-pedantic

cpp/template/weak/Template.h:16:3: error: C++98 requires newline at end of file

Commit a76a429bf91a9e0eb319cbd69833418b9b1110e2